# Generated by Django 3.2 on 2021-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
