# Generated by Django 3.2 on 2021-04-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_category_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jourj',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
